name: release
on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Get Git tag
        id: extract_git_tag
        run: |
          git_tag=${GITHUB_REF##*/}
          echo "GIT_TAG=${git_tag#v}" >> $GITHUB_ENV
          echo "git_tag=${git_tag#v}" >> $GITHUB_OUTPUT
          echo "Tag: ${git_tag#v}"

      - name: Set Project Version
        run: mvn versions:set -DnewVersion=${{env.GIT_TAG}}

      - name: Maven Build
        run: |
          mvn -B clean compile package -Dmaven.test.skip
          mkdir ./target/dist
          mv ./target/tomato-${{env.GIT_TAG}} ./target/dist/

      - uses: actions/upload-artifact@v4
        with:
          name: tomato-${{env.GIT_TAG}}
          retention-days: 5
          path: ./target/dist

    outputs:
      git_tag: ${{ steps.extract_git_tag.outputs.git_tag }}

  release-windows:
    needs: [build]
    timeout-minutes: 10
    runs-on: windows-2022

    env:
      GIT_TAG: ${{ needs.build.outputs.git_tag }}

    steps:
      - uses: microsoft/setup-msbuild@v2

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tomato-${{env.GIT_TAG}}
          path: ./target

      - name: Build AppImage
        run: |
          jpackage `
          --type app-image `
          --name Tomato `
          --app-version $env:GIT_TAG `
          --vendor Tomato `
          --icon ./build-windows/favicon.ico `
          --input ./target/tomato-$env:GIT_TAG `
          --main-jar tomato-$env:GIT_TAG.jar `
          --main-class io.github.clagomess.tomato.Main `
          --java-options "-splash:`$APPDIR/splash.png -Dfile.encoding=UTF-8" `
          --dest ./build-windows `
          --verbose
          mv ./build-windows/Tomato ./build-windows/tomato-$env:GIT_TAG-x64
          mkdir ./build-windows/dist
          cp -R ./build-windows/tomato-$env:GIT_TAG-x64 ./build-windows/dist/

      - uses: actions/upload-artifact@v4
        with:
          name: tomato-${{env.GIT_TAG}}-x64-win-portable
          retention-days: 5
          path: ./build-windows/dist

      - name: Find SignToolPath
        run: |
          $SignToolPath = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\bin\**\x64" `
          -Recurse -Filter "signtool.exe" | Select-Object -ExpandProperty FullName -First 1
          echo "SignTool Path: $SignToolPath"
          echo "SIGNTOOL_PATH=$SignToolPath" >> $env:GITHUB_ENV

      - name: Get Cert
        run: |
          [System.Convert]::FromBase64String("${{ secrets.CODE_SIGN_CERT_PFX }}") | Set-Content -Path ./build-windows/code-sign-ks.pfx -AsByteStream

      - name: InnoSetup Build
        run: |
          ISCC.exe `
          /DMyAppVersion=${{env.GIT_TAG}} `
          ./build-windows/tomato-inno-setup.iss
          
      - name: Sign Setup
        run: |
          & "${{env.SIGNTOOL_PATH}}" sign /v `
          /td SHA256 `
          /tr http://timestamp.digicert.com `
          /f "./build-windows/code-sign-ks.pfx" `
          /p "${{ secrets.CODE_SIGN_CERT_PASS }}" `
          /fd SHA256 `
          "./build-windows/tomato-$env:GIT_TAG-x64.exe"

      - uses: actions/upload-artifact@v4
        with:
          name: tomato-${{env.GIT_TAG}}-x64.exe
          compression-level: 0
          retention-days: 5
          path: ./build-windows/tomato-${{env.GIT_TAG}}-x64.exe

  release-linux:
    needs: [build]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        dist: [
          debian,
          fedora,
          flatpak
        ]

    env:
      GIT_TAG: ${{ needs.build.outputs.git_tag }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tomato-${{env.GIT_TAG}}
          path: ./target/dist

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker run --rm --privileged \
          -v "./build-${{matrix.dist}}:/opt/result" \
          -v "./target/dist/tomato-${{env.GIT_TAG}}:/opt/release" \
          -e GIT_TAG=${{env.GIT_TAG}} \
          ghcr.io/clagomess/tomato-build-${{matrix.dist}}
          
      - uses: actions/upload-artifact@v4
        with:
          name: tomato-linux-${{env.GIT_TAG}}-${{matrix.dist}}
          retention-days: 5
          path: ./build-${{matrix.dist}}/tomato-${{env.GIT_TAG}}*
