name: test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:
  junit:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Maven
        run: mvn test package
