name: test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
    paths:
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  junit:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-junit-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Maven
        run: mvn test package

  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-lint-${{ hashFiles('**/pom.xml') }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Maven
        run: mvn compile -Dmaven.test.skip -Dmaven.compiler.showDeprecation=true -Dmaven.compiler.failOnWarning=true
